export {
  dashboardApi,
  useGetCustomerInsightsQuery,
  useGetDashboardOverviewQuery,
  useGetRecentTransactionsQuery,
  useGetRevenueBreakdownQuery,
  useGetSalesPerformanceQuery,
  useGetTopProductsQuery,
  usePrefetchDashboardOverview,
} from "./dashboard-api"
export type {
  CustomerGrowthPoint,
  CustomerInsightsResponse,
  DashboardCustomer,
  DashboardMetric,
  DashboardOverviewResponse,
  DemographicRow,
  RecentTransaction,
  RegionRow,
  RevenueBreakdownItem,
  SalesPerformancePoint,
  SalesPerformanceQueryParams,
  TopProduct,
  TrendDirection,
} from "./types"