"use client"

import { useEffect } from "react"
import { useLocale } from "next-intl"

const EXACT: Record<string, string> = {
  // --- Navigation / sections ---
  "Administration": "الإدارة",
  "Agence": "الوكالة",
  "Alertes par defaut": "إعدادات التنبيهات الافتراضية",
  "Categories de vehicules": "فئات المركبات",
  "Categorie": "الفئة",
  "Clients": "العملاء",
  "Client": "العميل",
  "Documents": "الوثائق",
  "Flotte": "الأسطول",
  "Maintenance & vidanges": "الصيانة وتغيير الزيت",
  "Marques": "العلامات",
  "Paiements": "المدفوعات",
  "Paiement": "الدفع",
  "Parametres": "الإعدادات",
  "Reservations": "الحجوزات",
  "Roles": "الأدوار",
  "Roles et permissions": "الأدوار والصلاحيات",
  "Tableau de bord": "لوحة التحكم",
  "Utilisateurs": "المستخدمون",
  "Utilisateur": "المستخدم",
  "Vehicules": "المركبات",
  "Vehicule": "المركبة",
  "Vehicules disponibles": "المركبات المتوفرة",
  "Disponibilites": "التوفر",
  "Navigation": "التنقل",

  // --- Boutons / actions communs ---
  "Ajouter": "إضافة",
  "Ajouter maintenance": "إضافة صيانة",
  "Ajouter un vehicule": "إضافة مركبة",
  "Ajouter une marque": "إضافة علامة",
  "Ajouter un client": "إضافة عميل",
  "Ajouter un utilisateur": "إضافة مستخدم",
  "Ajouter une categorie": "إضافة فئة",
  "Annuler": "إلغاء",
  "Actualiser": "تحديث",
  "Actualiser les marques": "تحديث العلامات",
  "Appliquer": "تطبيق",
  "Cloturer": "إغلاق",
  "Cloturer la reservation": "إغلاق الحجز",
  "Confirmer": "تأكيد",
  "Confirmer la suppression": "تأكيد الحذف",
  "Creer": "إنشاء",
  "Creer la reservation": "إنشاء الحجز",
  "Creer le role": "إنشاء الدور",
  "Enregistrer": "حفظ",
  "Enregistrer une vidange": "تسجيل تغيير الزيت",
  "Exporter": "تصدير",
  "Importer": "استيراد",
  "Fermer": "إغلاق",
  "Filtrer": "تصفية",
  "Filtres": "المرشحات",
  "Generer un document": "إنشاء وثيقة",
  "Modifier": "تعديل",
  "Nouveau": "جديد",
  "Precedent": "السابق",
  "Rechercher": "بحث",
  "Recherche": "بحث",
  "Reinitialiser": "إعادة تعيين",
  "Retour": "رجوع",
  "Suivant": "التالي",
  "Supprimer": "حذف",
  "Supprimer la marque": "حذف العلامة",
  "Supprimer la reservation": "حذف الحجز",
  "Supprimer le client": "حذف العميل",
  "Supprimer le paiement": "حذف الدفعة",
  "Supprimer le role": "حذف الدور",
  "Supprimer le vehicule": "حذف المركبة",
  "Supprimer les clients": "حذف العملاء",
  "Supprimer les utilisateurs": "حذف المستخدمين",
  "Supprimer les vehicules": "حذف المركبات",
  "Selectionner tout": "تحديد الكل",
  "Selectionner tous les clients": "تحديد كل العملاء",
  "Selectionner tous les utilisateurs": "تحديد كل المستخدمين",
  "Voir": "عرض",
  "Voir tout": "عرض الكل",
  "Voir le detail": "عرض التفاصيل",
  "Telecharger le recu": "تحميل الإيصال",
  "Contacter le client": "الاتصال بالعميل",

  // --- Champs / labels ---
  "Actions": "الإجراءات",
  "Actif": "نشط",
  "Actifs": "نشطون",
  "Active": "نشطة",
  "Actives": "نشطة",
  "Inactif": "غير نشط",
  "Inactifs": "غير نشطين",
  "Inactive": "غير نشطة",
  "Inactives": "غير نشطة",
  "Adresse": "العنوان",
  "Adresse *": "العنوان *",
  "Adresse complete": "العنوان الكامل",
  "Annee": "السنة",
  "Annee / Couleur": "السنة / اللون",
  "Annee en cours": "السنة الحالية",
  "Assurance": "التأمين",
  "Bientot": "قريباً",
  "CIN": "البطاقة الوطنية",
  "CIN:": "البطاقة الوطنية:",
  "Caution": "الضمان",
  "Champs": "الحقول",
  "Chargement...": "جاري التحميل...",
  "Colonnes": "الأعمدة",
  "Compte actif": "حساب نشط",
  "Couleur": "اللون",
  "Couleur:": "اللون:",
  "Couleur par defaut": "اللون الافتراضي",
  "Date": "التاريخ",
  "Date *": "التاريخ *",
  "Date creation": "تاريخ الإنشاء",
  "Date de debut *": "تاريخ البدء *",
  "Date de depart *": "تاريخ الانطلاق *",
  "Date de fin *": "تاريخ الانتهاء *",
  "Date de retour *": "تاريخ الإرجاع *",
  "Date debut": "تاريخ البدء",
  "Date fin": "تاريخ الانتهاء",
  "Date debut location": "تاريخ بدء الكراء",
  "Date fin location": "تاريخ انتهاء الكراء",
  "Description": "الوصف",
  "Email": "البريد الإلكتروني",
  "Email *": "البريد الإلكتروني *",
  "Email:": "البريد الإلكتروني:",
  "En attente": "في الانتظار",
  "En cours": "قيد التنفيذ",
  "En retard": "متأخر",
  "Encaisse": "محصّل",
  "Heure de prise en charge": "ساعة الاستلام",
  "Heure de retour": "ساعة الإرجاع",
  "Heure prise en charge": "ساعة الاستلام",
  "Heure retour": "ساعة الإرجاع",
  "Historique kilometrage": "سجل الكيلومترات",
  "Immatriculation:": "رقم التسجيل:",
  "Informations client": "معلومات العميل",
  "Kilometrage": "الكيلومترات",
  "Kilometrage actuel": "الكيلومترات الحالية",
  "Label": "التسمية",
  "Largeur": "العرض",
  "Lieu de prise en charge": "مكان الاستلام",
  "Lieu de retour": "مكان الإرجاع",
  "Lieu prise en charge": "مكان الاستلام",
  "Lieu retour": "مكان الإرجاع",
  "Lieux": "الأماكن",
  "Liste des vehicules": "قائمة المركبات",
  "Marque": "العلامة",
  "Marque:": "العلامة:",
  "Matricule": "رقم التسجيل",
  "Methode *": "الطريقة *",
  "Modele": "الطراز",
  "Montant": "المبلغ",
  "Montant (MAD) *": "المبلغ (درهم) *",
  "Montant total": "المبلغ الإجمالي",
  "Nationalite": "الجنسية",
  "Nationalite *": "الجنسية *",
  "Niveau": "المستوى",
  "No. permis": "رقم الرخصة",
  "No. permis *": "رقم الرخصة *",
  "Nom": "الاسم",
  "Nom complet": "الاسم الكامل",
  "Nom complet *": "الاسم الكامل *",
  "Nombre de colonnes": "عدد الأعمدة",
  "Nombre de jours": "عدد الأيام",
  "Nombre de places": "عدد المقاعد",
  "Notes": "ملاحظات",
  "Notes (optionnel)": "ملاحظات (اختياري)",
  "Numero de chassis": "رقم الهيكل",
  "Numero de telephone": "رقم الهاتف",
  "Numero du permis": "رقم الرخصة",
  "Optionnel": "اختياري",
  "Passeport": "جواز السفر",
  "Periode": "الفترة",
  "Periode :": "الفترة:",
  "Periode de location": "فترة الكراء",
  "Permis:": "الرخصة:",
  "Permis delivre le *": "تاريخ إصدار الرخصة *",
  "Permis expire le *": "تاريخ انتهاء الرخصة *",
  "Date de delivrance du permis": "تاريخ إصدار الرخصة",
  "Date d'expiration du permis": "تاريخ انتهاء الرخصة",
  "Date d’expiration du permis": "تاريخ انتهاء الرخصة",
  "Photos du vehicule": "صور المركبة",
  "Photo ou scan CIN/passeport": "صورة أو مسح البطاقة/جواز السفر",
  "Photo ou scan du permis": "صورة أو مسح الرخصة",
  "Prix": "السعر",
  "Prix / jour": "السعر / اليوم",
  "Prix par jour": "السعر لكل يوم",
  "Prix par jour (MAD) *": "السعر لكل يوم (درهم) *",
  "Prix loue / jour": "سعر الكراء / اليوم",
  "Mot de passe": "كلمة المرور",
  "Reference": "المرجع",
  "Reference / facture": "المرجع / الفاتورة",
  "Reference (optionnel)": "المرجع (اختياري)",
  "Reservation *": "الحجز *",
  "Restant": "المتبقي",
  "Restant du": "المبلغ المتبقي",
  "Statut": "الحالة",
  "Statut de paiement": "حالة الدفع",
  "Statut de reservation": "حالة الحجز",
  "Statut reservation": "حالة الحجز",
  "Telephone:": "الهاتف:",
  "Telephone *": "الهاتف *",
  "Titre": "العنوان",
  "Titre section": "عنوان القسم",
  "Tous les statuts": "كل الحالات",
  "Tous les types": "كل الأنواع",
  "Tous les roles": "كل الأدوار",
  "Tout paiement": "كل المدفوعات",
  "Toutes categories": "كل الفئات",
  "Toutes methodes": "كل الطرق",
  "Toutes les permissions": "كل الصلاحيات",
  "Type": "النوع",
  "Type *": "النوع *",
  "Type de carburant": "نوع الوقود",
  "Valeur": "القيمة",
  "Ville": "المدينة",
  "Ville *": "المدينة *",
  "Vidange": "تغيير الزيت",
  "Visite technique": "الفحص التقني",
  "Vignette": "الضريبة",
  "jours": "أيام",
  "km": "كم",

  // --- Maintenance ---
  "Maintenance libre": "صيانة حرة",
  "Maintenances hors vidange": "صيانة خارج تغيير الزيت",
  "Gestion des marques": "إدارة العلامات",
  "Gestion des reservations et locations de vehicules.": "إدارة الحجوزات وكراء المركبات.",
  "Gestion de la flotte, documents administratifs, photos, tarifs et disponibilite.": "إدارة الأسطول والوثائق الإدارية والصور والأسعار والتوفر.",
  "Suivi par vehicule": "المتابعة حسب المركبة",
  "Vidange en retard": "تغيير الزيت متأخر",
  "Nouveau kilometrage (km) *": "الكيلومترات الجديدة (كم) *",
  "Derniere vidange (date)": "آخر تغيير زيت (التاريخ)",
  "Derniere vidange (km)": "آخر تغيير زيت (كم)",
  "Intervalle vidange (km)": "فترة تغيير الزيت (كم)",
  "Ancien": "السابق",
  "Accident": "حادث",
  "Libre": "حر",
  "A jour": "محدّث",
  "À jour": "محدّث",

  // --- Statuts ---
  "Confirmee": "مؤكد",
  "Annulee": "ملغى",
  "Terminee": "منتهي",
  "Disponible": "متاح",
  "Disponibles": "متوفرة",
  "Indisponibles": "غير متوفرة",
  "Louees": "مكراة",
  "Non disponible": "غير متاح",
  "Non classe": "غير مصنف",
  "Non cloturee": "غير مغلق",
  "Non renseigne": "غير محدد",
  "Non renseignee": "غير محددة",
  "Depart non precise": "الانطلاق غير محدد",
  "Retour non precise": "الإرجاع غير محدد",
  "Sans role": "بدون دور",

  // --- Documents éditeur ---
  "Apercu": "معاينة",
  "Apercu du document": "معاينة الوثيقة",
  "Aucun template selectionne.": "لم يتم تحديد أي قالب.",
  "Ajoutez une section depuis le panneau gauche.": "أضف قسماً من اللوحة اليسرى.",
  "Alignement": "المحاذاة",
  "Bas": "أسفل",
  "Haut": "أعلى",
  "Gauche": "يسار",
  "Droite": "يمين",
  "Canvas vide": "لوحة فارغة",
  "Cliquez sur un element du canvas.": "انقر على عنصر في اللوحة.",
  "Cliquez sur une section.": "انقر على قسم.",
  "Calendrier": "التقويم",
  "Contenu": "المحتوى",
  "Couleurs": "الألوان",
  "Couleur bordure": "لون الحدود",
  "Couleur de fond": "لون الخلفية",
  "Couleur en-tete": "لون الترويسة",
  "Couleur label": "لون التسمية",
  "Couleur ligne": "لون السطر",
  "Couleur principale": "اللون الرئيسي",
  "Couleur texte": "لون النص",
  "Document": "الوثيقة",
  "Documents ajoutes": "الوثائق المضافة",
  "Document assurance": "وثيقة التأمين",
  "Document carte grise": "وثيقة البطاقة الرمادية",
  "Document non renseigne": "وثيقة غير محددة",
  "Double": "مزدوج",
  "Elements": "العناصر",
  "Epaisseur": "السمك",
  "Epaisseur bordure": "سمك الحدود",
  "Espace": "مسافة",
  "Espace entre colonnes (px)": "المسافة بين الأعمدة (بكسل)",
  "Espacement": "التباعد",
  "Espacement interne": "التباعد الداخلي",
  "Espacement lettres": "تباعد الأحرف",
  "Fond": "الخلفية",
  "Fond & Bordure": "الخلفية والحدود",
  "Fond du document": "خلفية الوثيقة",
  "Fond en-tete": "خلفية الترويسة",
  "Format page": "تنسيق الصفحة",
  "Format CSS: haut droite bas gauche": "تنسيق CSS: أعلى يمين أسفل يسار",
  "Graisse": "السماكة",
  "Grille info": "شبكة المعلومات",
  "Hauteur (px)": "الارتفاع (بكسل)",
  "Image": "صورة",
  "Image / Logo": "صورة / شعار",
  "Interligne": "تباعد الأسطر",
  "Italique": "مائل",
  "Marge bas": "الهامش السفلي",
  "Marge haut": "الهامش العلوي",
  "Marges (margin)": "الهوامش",
  "Mise en page": "تخطيط الصفحة",
  "Mon titre": "عنواني",
  "Nombre de colonnes ": "عدد الأعمدة ",
  "Normal": "عادي",
  "Padding (ex: 16px 24px)": "الحشو (مثال: 16px 24px)",
  "Points": "نقاط",
  "Police principale": "الخط الرئيسي",
  "Rayon": "نصف القطر",
  "Rembourrage (padding)": "الحشو الداخلي",
  "Sections": "الأقسام",
  "Separateur": "فاصل",
  "Signature": "التوقيع",
  "Signature client": "توقيع العميل",
  "Solide": "صلب",
  "Sous-texte": "نص فرعي",
  "Style": "النمط",
  "Style bordure": "نمط الحدود",
  "Tableau": "جدول",
  "Tableau paiements": "جدول المدفوعات",
  "Taille label": "حجم التسمية",
  "Taille nom": "حجم الاسم",
  "Taille police": "حجم الخط",
  "Taille valeur": "حجم القيمة",
  "Texte": "نص",
  "Tirets": "شرطات",
  "Typographie": "الطباعة",
  "Typographie globale": "الطباعة العامة",
  "Validation": "التحقق",
  "Variables": "المتغيرات",
  "URL": "الرابط",
  "Imprimer la facture de paiement favorite": "طباعة فاتورة الدفع المفضلة",
  "Imprimer le contrat favori": "طباعة العقد المفضل",
  "Imprimer la facture": "طباعة الفاتورة",
  "Gerer les paiements": "إدارة المدفوعات",
  "Retrouvez-le dans Documents > Generes.": "ستجده في الوثائق > المُنشأة.",

  // --- Méthodes de paiement ---
  "Especes": "نقداً",
  "Carte": "بطاقة",
  "Carte bancaire": "بطاقة بنكية",
  "Virement": "تحويل بنكي",
  "Cheque": "شيك",
  "Rembourse": "مُسترجع",
  "Paiement complet": "دفع كامل",
  "Paiement partiel": "دفع جزئي",

  // --- Titres / sous-titres de page ---
  "H1 — Grand titre": "H1 — عنوان كبير",
  "H2 — Sous-titre": "H2 — عنوان فرعي",
  "H3 — Petit titre": "H3 — عنوان صغير",
  "Tarification & statuts": "التسعير والحالات",
  "Calcul du benefice": "حساب الربح",
  "Benefice total:": "إجمالي الربح:",
  "Benefice/jour:": "الربح/اليوم:",
  "Prix client/jour:": "سعر العميل/اليوم:",
  "Prix reel/jour:": "السعر الحقيقي/اليوم:",
  "Prix/jour:": "السعر/اليوم:",
  "Total cout reel:": "إجمالي التكلفة الحقيقية:",
  "Total location:": "إجمالي الكراء:",
  "Total reservation": "إجمالي الحجز",
  "Total :": "الإجمالي:",
  "Total paye": "المبلغ المدفوع",
  "Total transactions": "إجمالي المعاملات",
  "Total location": "إجمالي الكراء",
  "Vehicule disponible": "مركبة متوفرة",
  "Vehicule reloue": "مركبة معاد كراؤها",
  "Vehicule :": "المركبة:",
  "Client :": "العميل:",
  "Acompte initial (MAD)": "العربون الأولي (درهم)",
  "Garantie / caution (MAD)": "الضمان / الكفالة (درهم)",
  "Methode de l'acompte": "طريقة العربون",
  "Methode de la garantie": "طريقة الضمان",
  "Montant deja encaisse lors de la reservation": "المبلغ المحصّل مسبقاً عند الحجز",
  "Coût (MAD)": "التكلفة (درهم)",
  "Boite de vitesse": "علبة السرعة",

  // --- Phrases descriptives ---
  "Aucun client ne correspond aux filtres.": "لا يوجد أي عميل يطابق المرشحات.",
  "Aucun client trouve.": "لم يتم العثور على أي عميل.",
  "Aucun document proche de l'expiration": "لا توجد وثائق قريبة من الانتهاء",
  "Aucun fichier": "لا يوجد ملف",
  "Aucun paiement ne correspond aux filtres.": "لا توجد أي دفعة تطابق المرشحات.",
  "Aucun role ne correspond aux filtres appliques.": "لا يوجد أي دور يطابق المرشحات المطبقة.",
  "Aucun role trouve.": "لم يتم العثور على أي دور.",
  "Aucun utilisateur ne correspond aux filtres appliques.": "لا يوجد أي مستخدم يطابق المرشحات المطبقة.",
  "Aucun utilisateur trouve.": "لم يتم العثور على أي مستخدم.",
  "Aucun vehicule dans la flotte.": "لا توجد مركبات في الأسطول.",
  "Aucun vehicule disponible pour cette periode.": "لا توجد مركبة متوفرة لهذه الفترة.",
  "Aucun vehicule ne correspond aux filtres.": "لا توجد أي مركبة تطابق المرشحات.",
  "Aucun vehicule trouve.": "لم يتم العثور على أي مركبة.",
  "Aucune categorie vehicule.": "لا توجد فئة مركبات.",
  "Aucune description": "لا يوجد وصف",
  "Aucune donnee disponible.": "لا توجد بيانات متاحة.",
  "Aucune maintenance accident/libre enregistree.": "لا توجد صيانة حادث أو حرة مسجلة.",
  "Aucune marque ne correspond aux filtres.": "لا توجد أي علامة تطابق المرشحات.",
  "Aucune reservation ne correspond aux filtres.": "لا توجد أي حجوزات تطابق المرشحات.",
  "Aucune reservation trouvee.": "لم يتم العثور على أي حجز.",
  "Choisir un vehicule...": "اختر مركبة...",
  "Choisir un client...": "اختر عميلاً...",
  "Choisir le statut": "اختر الحالة",
  "Choisir": "اختر",
  "Choisissez la reservation source.": "اختر الحجز المصدر.",
  "Chargement des roles...": "جاري تحميل الأدوار...",
  "Chargement des utilisateurs...": "جاري تحميل المستخدمين...",
  "Creation en etapes avec client, documents, vehicule et paiement.": "إنشاء على مراحل مع العميل والوثائق والمركبة والدفع.",
  "Creation vehicule": "إنشاء مركبة",
  "La date de fin doit etre posterieure ou egale a la date de debut.": "يجب أن يكون تاريخ الانتهاء بعد أو يساوي تاريخ البدء.",
  "Renseignez les details de la location de vehicule.": "أدخل تفاصيل كراء المركبة.",
  "Selectionner le client *": "اختر العميل *",
  "Selectionner une reservation...": "اختر حجزاً...",
  "Selectionnez une periode valide.": "اختر فترة صالحة.",
  "Saisir le kilometrage de retour.": "أدخل كيلومترات الإرجاع.",
  "Mouvements de kilometrage du vehicule.": "حركات كيلومترات المركبة.",
  "Modification manuelle": "تعديل يدوي",
  "Laisser vide pour conserver": "اتركه فارغاً للإبقاء عليه",
  "Retour reservation": "إرجاع الحجز",

  // --- Formats document ---
  "A4 (210×297 mm)": "A4 (210×297 ملم)",
  "Letter (216×279 mm)": "Letter (216×279 ملم)",
  "Bold 700": "عريض 700",
  "ExtraBold 800": "عريض جداً 800",
  "SemiBold 600": "شبه عريض 600",
  "Medium 500": "متوسط 500",
  "Normal 400": "عادي 400",
  "Light 300": "خفيف 300",

  // --- Messages toast / erreurs ---
  "Client cree avec succes.": "تم إنشاء العميل بنجاح.",
  "Client modifie avec succes.": "تم تعديل العميل بنجاح.",
  "Client supprime.": "تم حذف العميل.",
  "Contrat pret pour impression.": "العقد جاهز للطباعة.",
  "Facture prete pour impression.": "الفاتورة جاهزة للطباعة.",
  "Document genere.": "تم إنشاء الوثيقة.",
  "Marque creee avec succes.": "تم إنشاء العلامة بنجاح.",
  "Marque mise a jour avec succes.": "تم تحديث العلامة بنجاح.",
  "Marque supprimee avec succes.": "تم حذف العلامة بنجاح.",
  "Paiement enregistre.": "تم تسجيل الدفعة.",
  "Paiement mis a jour.": "تم تحديث الدفعة.",
  "Paiement supprime.": "تم حذف الدفعة.",
  "Reservation cloturee.": "تم إغلاق الحجز.",
  "Reservation creee avec succes.": "تم إنشاء الحجز بنجاح.",
  "Reservation modifiee avec succes.": "تم تعديل الحجز بنجاح.",
  "Reservation supprimee.": "تم حذف الحجز.",
  "Role cree.": "تم إنشاء الدور.",
  "Role mis a jour.": "تم تحديث الدور.",
  "Role supprime.": "تم حذف الدور.",
  "Statut mis a jour.": "تم تحديث الحالة.",
  "Statuts mis a jour.": "تم تحديث الحالات.",
  "Template sauvegarde.": "تم حفظ القالب.",
  "Une erreur est survenue.": "حدث خطأ.",
  "Utilisateur cree.": "تم إنشاء المستخدم.",
  "Utilisateurs supprimes.": "تم حذف المستخدمين.",
  "Vehicule cree avec succes.": "تم إنشاء المركبة بنجاح.",
  "Vehicule mis a jour.": "تم تحديث المركبة.",
  "Vehicule supprime.": "تم حذف المركبة.",
  "Confirmez la suppression.": "أكّد الحذف.",
  "Confirmez la suppression de ce client.": "أكّد حذف هذا العميل.",
  "Confirmez la suppression de cette marque.": "أكّد حذف هذه العلامة.",
  "Cette action supprimera definitivement les clients selectionnes.": "سيؤدي هذا الإجراء إلى حذف العملاء المحددين نهائياً.",
  "Cette action supprimera definitivement les reservations selectionnees.": "سيؤدي هذا الإجراء إلى حذف الحجوزات المحددة نهائياً.",
  "Cette action supprimera les vehicules selectionnes et leurs documents.": "سيؤدي هذا الإجراء إلى حذف المركبات المحددة ووثائقها.",
  "Impossible d'enregistrer la marque pour le moment.": "تعذّر حفظ العلامة في الوقت الحالي.",
  "Impossible d'enregistrer la reservation.": "تعذّر حفظ الحجز.",
  "Impossible d'enregistrer le client.": "تعذّر حفظ العميل.",
  "Impossible d'enregistrer le paiement.": "تعذّر حفظ الدفعة.",
  "Impossible d'enregistrer le vehicule.": "تعذّر حفظ المركبة.",
  "Impossible d'enregistrer les parametres.": "تعذّر حفظ الإعدادات.",
  "Impossible d'imprimer la facture.": "تعذّرت طباعة الفاتورة.",
  "Impossible d'imprimer le contrat.": "تعذّرت طباعة العقد.",
  "Impossible de charger les clients.": "تعذّر تحميل العملاء.",
  "Impossible de charger les marques.": "تعذّر تحميل العلامات.",
  "Impossible de charger les paiements.": "تعذّر تحميل المدفوعات.",
  "Impossible de charger les reservations.": "تعذّر تحميل الحجوزات.",
  "Impossible de charger les roles.": "تعذّر تحميل الأدوار.",
  "Impossible de charger les utilisateurs pour le moment.": "تعذّر تحميل المستخدمين في الوقت الحالي.",
  "Impossible de charger les vehicules.": "تعذّر تحميل المركبات.",
  "Impossible de cloturer la reservation.": "تعذّر إغلاق الحجز.",
  "Impossible de creer le role.": "تعذّر إنشاء الدور.",
  "Impossible de mettre a jour le role.": "تعذّر تحديث الدور.",
  "Impossible de mettre a jour le statut.": "تعذّر تحديث الحالة.",
  "Impossible de modifier les statuts.": "تعذّر تعديل الحالات.",
  "Impossible de supprimer la marque.": "تعذّر حذف العلامة.",
  "Impossible de supprimer la reservation.": "تعذّر حذف الحجز.",
  "Impossible de supprimer le client.": "تعذّر حذف العميل.",
  "Impossible de supprimer le paiement.": "تعذّر حذف الدفعة.",
  "Impossible de supprimer le role.": "تعذّر حذف الدور.",
  "Impossible de supprimer le vehicule.": "تعذّر حذف المركبة.",
  "Impossible de supprimer les clients.": "تعذّر حذف العملاء.",
  "Impossible de supprimer les marques.": "تعذّر حذف العلامات.",
  "Impossible de supprimer les reservations.": "تعذّر حذف الحجوزات.",
  "Impossible de supprimer les vehicules.": "تعذّر حذف المركبات.",

  // --- Dialogues / titres ---
  "Modifier la marque": "تعديل العلامة",
  "Modifier la reservation": "تعديل الحجز",
  "Modifier le client": "تعديل العميل",
  "Modifier le paiement": "تعديل الدفعة",
  "Modifier le role": "تعديل الدور",
  "Modifier le statut": "تعديل الحالة",
  "Modifier le vehicule": "تعديل المركبة",
  "Modifiez les details du paiement.": "عدّل تفاصيل الدفعة.",
  "Nouveau paiement": "دفعة جديدة",
  "Nouveau role": "دور جديد",
  "Nouveau client": "عميل جديد",
  "Nouvelle reservation": "حجز جديد",
  "Enregistrez un paiement sur une reservation existante.": "سجّل دفعة على حجز موجود.",
  "Apercu de la marque": "معاينة العلامة",
  "Activer les clients": "تفعيل العملاء",
  "Desactiver les clients": "إلغاء تفعيل العملاء",
  "Paiements de la reservation": "مدفوعات الحجز",
  "Paiement complet ": "دفع كامل ",

  // --- Sections documents identité ---
  "CIN / passeport recto": "البطاقة/جواز السفر (الوجه)",
  "CIN / passeport verso": "البطاقة/جواز السفر (الظهر)",
  "Permis recto": "الرخصة (الوجه)",
  "Permis verso": "الرخصة (الظهر)",
  "Periode & Vehicule": "الفترة والمركبة",
  "Client / Vehicule": "العميل / المركبة",
  "Expiration assurance": "انتهاء التأمين",
  "Expiration vignette": "انتهاء الضريبة",
  "Expiration visite technique": "انتهاء الفحص التقني",

  // ===== Dashboard =====
  "Indicateurs cles": "المؤشرات الرئيسية",
  "Chiffre d'affaires": "رقم المعاملات",
  "CA": "رقم المعاملات",
  "CA du mois": "رقم معاملات الشهر",
  "Repartition du chiffre d'affaires": "توزيع رقم المعاملات",
  "Distribution du CA par canal": "توزيع رقم المعاملات حسب القناة",
  "Evolution du CA sur les 6 derniers mois": "تطور رقم المعاملات خلال الأشهر الستة الأخيرة",
  "Selectionner un canal": "اختر قناة",
  "Performance des ventes": "أداء المبيعات",
  "Ventes": "المبيعات",
  "Revenus": "الإيرادات",
  "Revenus mensuels": "الإيرادات الشهرية",
  "Ventes mensuelles vs objectifs": "المبيعات الشهرية مقابل الأهداف",
  "Ventes ponctuelles": "مبيعات ظرفية",
  "Objectif": "الهدف",
  "Part": "النسبة",
  "Region": "المنطقة",
  "Regions": "المناطق",
  "Profils": "الملفات",
  "Tranche d'age": "الفئة العمرية",
  "Croissance": "النمو",
  "Croissance, profils et zones geographiques": "النمو والملفات والمناطق الجغرافية",
  "Apercu clients": "نظرة عامة على العملاء",
  "Evolution de la clientele": "تطور قاعدة العملاء",
  "Clients actifs": "عملاء نشطون",
  "Clients ayant commande": "عملاء قاموا بالطلب",
  "Clients fideles": "عملاء أوفياء",
  "Clients perdus": "عملاء مفقودون",
  "Clients totaux": "إجمالي العملاء",
  "Nouveaux clients": "عملاء جدد",
  "Panier moyen": "متوسط السلة",
  "Moyenne boutique": "متوسط المتجر",
  "Taux de conversion": "نسبة التحويل",
  "Taux de retention": "نسبة الاحتفاظ",
  "Taux de retention ": "نسبة الاحتفاظ ",
  "Commandes": "الطلبات",
  "Commandes du mois": "طلبات الشهر",
  "Produits phares": "المنتجات الرائدة",
  "Meilleures performances du mois": "أفضل أداء للشهر",
  "Dernieres transactions clients": "آخر معاملات العملاء",
  "Transactions recentes": "المعاملات الأخيرة",
  "Reservations recentes": "الحجوزات الأخيرة",
  "Les 6 dernieres creees": "آخر 6 تم إنشاؤها",
  "Statut de la flotte": "حالة الأسطول",
  "Flotte aujourd'hui": "الأسطول اليوم",
  "Locations actives": "عمليات كراء نشطة",
  "Reste a percevoir": "المتبقي للتحصيل",
  "Mouvements du jour": "حركات اليوم",
  "Departs aujourd'hui": "الانطلاقات اليوم",
  "Retours aujourd'hui": "الإرجاعات اليوم",
  "Prises en charge prevues ce jour": "الاستلامات المتوقعة هذا اليوم",
  "Restitutions prevues ce jour": "الإرجاعات المتوقعة هذا اليوم",
  "Reservations non annulees demarrant ce mois": "الحجوزات غير الملغاة التي تبدأ هذا الشهر",
  "Cumul de tous les contrats non annules": "مجموع كل العقود غير الملغاة",
  "Somme du restant sur reservations actives": "مجموع المتبقي على الحجوزات النشطة",
  "Statut confirme ou actif chevauchant la date du jour": "حالة مؤكدة أو نشطة تتداخل مع تاريخ اليوم",
  "Vehicules avec reservation chevauchant aujourd'hui": "مركبات بحجز يتداخل مع اليوم",
  "Aucun revenu enregistre sur la periode": "لا توجد إيرادات مسجلة في الفترة",
  "vs mois precedent": "مقابل الشهر السابق",
  "En hausse ce mois-ci": "في ارتفاع هذا الشهر",
  "Engagement superieur aux objectifs": "تفاعل يفوق الأهداف",
  "Fidelisation solide": "ولاء قوي",
  "Progression reguliere": "تقدم منتظم",
  "Les projections de conversion sont atteintes": "تم تحقيق توقعات التحويل",
  "Le volume de commandes demande une attention": "حجم الطلبات يتطلب انتباهاً",
  "Recul de 2 % sur la periode": "تراجع بنسبة 2٪ خلال الفترة",
  "Europe": "أوروبا",
  "Asie-Pacifique": "آسيا والمحيط الهادئ",
  "Amerique du Nord": "أمريكا الشمالية",
  "Amerique latine": "أمريكا اللاتينية",
  "Autres": "أخرى",
  "Services": "الخدمات",
  "Abonnements": "الاشتراكات",
  "Accessoires": "الإكسسوارات",
  "Partenariats": "الشراكات",
  "Professionnel": "احترافي",

  // --- Placeholders de recherche / saisie ---
  "Rechercher...": "بحث...",
  "Rechercher client, vehicule...": "البحث عن عميل أو مركبة...",
  "Rechercher client, vehicule, matricule...": "البحث عن عميل أو مركبة أو رقم تسجيل...",
  "Rechercher matricule, marque...": "البحث عن رقم تسجيل أو علامة...",
  "Rechercher matricule, marque, modele...": "البحث عن رقم تسجيل أو علامة أو طراز...",
  "Rechercher nom, email, CIN, passeport...": "البحث عن اسم أو بريد أو بطاقة أو جواز سفر...",
  "Rechercher nom, telephone, email, CIN...": "البحث عن اسم أو هاتف أو بريد أو بطاقة...",
  "Rechercher par client ou vehicule...": "البحث حسب العميل أو المركبة...",
  "Rechercher par nom, e-mail, telephone, CIN ou poste": "البحث حسب الاسم أو البريد أو الهاتف أو البطاقة أو المنصب",
  "Rechercher un role": "البحث عن دور",
  "Rechercher une marque": "البحث عن علامة",
  "Rechercher une permission": "البحث عن صلاحية",
  "Rechercher une categorie": "البحث عن فئة",
  "Marque, modele, immatriculation...": "العلامة، الطراز، رقم التسجيل...",
  "Marque, modele, immatriculation": "العلامة، الطراز، رقم التسجيل",
  "Agence, aeroport...": "وكالة، مطار...",
  "Agence, hotel...": "وكالة، فندق...",
  "Clients etrangers": "عملاء أجانب",
  "Clients marocains": "عملاء مغاربة",
  "Etrangers": "أجانب",
  "Marocains": "مغاربة",
  "Etat du vehicule, observations...": "حالة المركبة، ملاحظات...",
  "Informations complementaires...": "معلومات إضافية...",
  "Minimum 8 caracteres": "8 أحرف على الأقل",
  "Confirmer le mot de passe": "تأكيد كلمة المرور",
  "Presentation courte de la marque": "وصف موجز للعلامة",
  "Remarque optionnelle...": "ملاحظة اختيارية...",
  "Remarque...": "ملاحظة...",
  "N° recu, reference virement...": "رقم الإيصال، مرجع التحويل...",
  "N° recu, virement...": "رقم الإيصال، تحويل...",
  "Couleur par defaut ": "اللون الافتراضي ",
  "Administrez les marques du catalogue avec la meme experience que les autres ecrans du back-office.": "أدر علامات الكتالوج بنفس تجربة باقي شاشات لوحة الإدارة.",
  "Gestion des comptes du personnel et des administrateurs. Filtrez par role, par statut ou par recherche libre.": "إدارة حسابات الموظفين والمسؤولين. صفِّ حسب الدور أو الحالة أو البحث الحر.",
  "Gestion des fiches clients, documents d'identite et permis de conduire.": "إدارة بطاقات العملاء ووثائق الهوية ورخص السياقة.",
  "Gestion des roles du back-office et des permissions associees.": "إدارة أدوار لوحة الإدارة والصلاحيات المرتبطة بها.",
  "Historique de tous les paiements enregistres.": "سجل كل المدفوعات المسجلة.",
  "Selectionnez une periode pour voir les vehicules disponibles. L'heure n'est pas requise; elle s'affiche dans la colonne de disponibilite lorsqu'un vehicule revient le jour meme.": "اختر فترة لعرض المركبات المتوفرة. الساعة غير مطلوبة؛ تظهر في عمود التوفر عندما تعود مركبة في نفس اليوم.",

  // --- Badges / en-tetes de page ---
  "LOCATION": "كراء",
  "Location": "كراء",
  "Catalogue": "الكتالوج",

  // --- En-tetes de tableaux ---
  "Identite": "الهوية",
  "Permis": "الرخصة",
  "Tarif": "التسعيرة",
  "Details": "التفاصيل",
  "Places": "المقاعد",
  "Disponibilite": "التوفر",
  "Resultats": "النتائج",
  "Net": "الصافي",
  "Encaisse ": "محصّل ",

  // --- Titres de listes / cartes ---
  "Liste des clients": "قائمة العملاء",
  "Liste des reservations": "قائمة الحجوزات",
  "Liste des utilisateurs": "قائمة المستخدمين",
  "Liste des marques": "قائمة العلامات",
  "Historique des paiements": "سجل المدفوعات",
  "Periode de disponibilite": "فترة التوفر",
  "Filtrer par vehicule": "تصفية حسب المركبة",
  "Afficher": "إظهار",
  "Masquer": "إخفاء",

  // --- Page profil ---
  "Compte": "الحساب",
  "Mon profil": "ملفي الشخصي",
  "Profil": "الملف الشخصي",
  "Modifiez vos informations personnelles et votre mot de passe.": "عدّل معلوماتك الشخصية وكلمة المرور.",
  "Informations personnelles": "المعلومات الشخصية",
  "Poste": "المنصب",
  "Mot de passe actuel": "كلمة المرور الحالية",
  "Nouveau mot de passe": "كلمة المرور الجديدة",
  "Modifier le mot de passe": "تغيير كلمة المرور",
  "Choisissez un mot de passe d'au moins 8 caracteres.": "اختر كلمة مرور من 8 أحرف على الأقل.",
  "Profil mis a jour.": "تم تحديث الملف الشخصي.",
  "Mot de passe mis a jour.": "تم تحديث كلمة المرور.",
  "Impossible de mettre a jour le profil.": "تعذّر تحديث الملف الشخصي.",
  "Impossible de mettre a jour le mot de passe.": "تعذّر تحديث كلمة المرور.",
  "Le nom est requis.": "الاسم مطلوب.",
  "Le mot de passe actuel est requis.": "كلمة المرور الحالية مطلوبة.",
  "Le nouveau mot de passe doit contenir au moins 8 caracteres.": "يجب أن تحتوي كلمة المرور الجديدة على 8 أحرف على الأقل.",
  "Les mots de passe ne correspondent pas.": "كلمتا المرور غير متطابقتين.",

  // --- Types de carburant / boite ---
  "Essence": "بنزين",
  "Diesel": "ديزل",
  "Hybride": "هجين",
  "Electrique": "كهربائي",
  "GPL": "غاز",
  "Manuelle": "يدوي",
  "Automatique": "أوتوماتيكي",
  "Essence - Manuelle": "بنزين - يدوي",
  "Essence - Automatique": "بنزين - أوتوماتيكي",
  "Diesel - Manuelle": "ديزل - يدوي",
  "Diesel - Automatique": "ديزل - أوتوماتيكي",

  // --- Categories vehicule ---
  "Berline": "سيارة سيدان",
  "Citadine": "سيارة مدينة",
  "SUV": "دفع رباعي",
  "Utilitaire": "نفعية",
  "Monospace": "عائلية",
  "Cabriolet": "مكشوفة",
  "Coupe": "كوبيه",
  "Break": "ستيشن",
  "Pickup": "بيك أب",
  "4x4": "دفع رباعي",

  // --- Couleurs ---
  "Rouge": "أحمر",
  "Bleu": "أزرق",
  "Gris": "رمادي",
  "Noir": "أسود",
  "Blanc": "أبيض",
  "Vert": "أخضر",
  "Jaune": "أصفر",
  "Orange": "برتقالي",
  "Marron": "بني",
  "Beige": "بيج",
  "Argent": "فضي",
  "GREEN": "أخضر",

  // --- Documents / statuts vehicule ---
  "ID OK": "الهوية سليمة",
  "Permis OK": "الرخصة سليمة",
  "Marocaine": "مغربية",
  "Etrangere": "أجنبية",

  // --- Dashboard : alertes & sous-titres ---
  "Vue d'ensemble de votre activite de location : revenus, flotte et mouvements du jour.": "نظرة عامة على نشاط الكراء: الإيرادات والأسطول وحركات اليوم.",
  "Vue d'ensemble de l'activité": "نظرة عامة على النشاط",
  "Documents a surveiller": "وثائق للمتابعة",
  "Vidanges a prevoir": "تغييرات زيت مرتقبة",
  "Aucune vidange a prevoir pour le moment": "لا توجد تغييرات زيت مرتقبة حالياً",
  "Top vehicules par revenus": "أفضل المركبات حسب الإيرادات",
  "Indicateurs locations": "مؤشرات الكراء",
  "Alertes maintenance": "تنبيهات الصيانة",
  "Actions rapides": "إجراءات سريعة",
}

const REPLACEMENTS: Array<[RegExp, string]> = [
  // ---- Fragments dynamiques (avec nombres) — appliques en premier ----
  // "N clients au total, M actifs." / "marques au total" / "M actives."
  [/\bclients au total\b/gi, "عملاء إجمالاً"],
  [/\bmarques au total\b/gi, "علامات إجمالاً"],
  [/\bau total\b/gi, "إجمالاً"],
  [/\bactifs\b/gi, "نشطون"],
  [/\bactives\b/gi, "نشطة"],
  [/\bpaiement\(s\)/gi, "دفعة/دفعات"],
  [/\breservation\(s\)/gi, "حجز/حجوزات"],
  [/\bvehicule\(s\)\s*affiches?\b/gi, "مركبة معروضة"],
  [/\bvehicule\(s\)/gi, "مركبة/مركبات"],
  [/\bvehicules disponibles\b/gi, "مركبات متوفرة"],
  [/\bRepartition des\b/gi, "توزيع"],
  [/\baujourd'hui\b/gi, "اليوم"],
  [/\baujourd’hui\b/gi, "اليوم"],
  // "expire depuis N j" / "expire aujourd'hui" / "N j restants" / "N jours restants"
  [/(\d+)\s*j\s+restants?\b/gi, "$1 يوم متبقٍ"],
  [/(\d+)\s*jours?\s+restants?\b/gi, "$1 يوم متبقٍ"],
  [/\bexpire depuis\s*(\d+)\s*j\b/gi, "منتهية منذ $1 يوم"],
  [/\bexpire dans\s*(\d+)\s*j\b/gi, "تنتهي خلال $1 يوم"],
  // ---- Profil : phrase avec username dynamique ----
  [/\bVotre nom d'utilisateur est\b/gi, "اسم المستخدم الخاص بك هو"],
  [/\bVotre nom d’utilisateur est\b/gi, "اسم المستخدم الخاص بك هو"],
  [/\bet ne peut pas etre modifie\.?/gi, "ولا يمكن تعديله."],
  [/\bet ne peut pas être modifié\.?/gi, "ولا يمكن تعديله."],
  // ---- Dashboard : fragments alertes (avec nombres) ----
  [/\bexpire\(s\)/gi, "منتهية"],
  [/\bbientot\b/gi, "قريباً"],
  [/\bbientôt\b/gi, "قريباً"],
  [/\ben retard\b/gi, "متأخر"],
  [/\bExpiration\s*:/gi, "الانتهاء:"],
  [/\bActuel\s*:/gi, "الحالي:"],
  [/\bProchaine\s*:/gi, "التالي:"],
  [/\bpar revenus\b/gi, "حسب الإيرادات"],
  [/\bTop vehicules\b/gi, "أفضل المركبات"],
  [/\bkm\b/g, "كم"],
  [/\ba surveiller\b/gi, "للمتابعة"],
  [/\bà surveiller\b/gi, "للمتابعة"],
  [/\ba prevoir\b/gi, "مرتقبة"],
  [/\bà prévoir\b/gi, "مرتقبة"],
  [/\bexpire aujourd'hui\b/gi, "تنتهي اليوم"],
  [/\bexpire aujourd’hui\b/gi, "تنتهي اليوم"],
  [/\bexpire depuis\b/gi, "منتهية منذ"],
  [/\bexpire dans\b/gi, "تنتهي خلال"],
  [/\bExpire le\b/gi, "تنتهي في"],
  [/\bexpire\b/gi, "تنتهي"],
  [/\brestants?\b/gi, "متبقٍ"],
  [/\bvehicules\b/gi, "مركبات"],
  [/\bvehicule\b/gi, "مركبة"],
  // labels documents véhicule (assurance/visite/vignette) avant les mots isolés
  [/\bVisite technique\b/gi, "الفحص التقني"],
  [/\bDernieres transactions\b/gi, "آخر المعاملات"],
  [/\bderniers mois\b/gi, "أشهر أخيرة"],
  [/\bdernieres creees\b/gi, "آخر ما أُنشئ"],
  [/\bvs le mois dernier\b/gi, "مقابل الشهر الماضي"],
  [/\bvs mois precedent\b/gi, "مقابل الشهر السابق"],
  [/\bce mois-ci\b/gi, "هذا الشهر"],
  [/\bdu mois\b/gi, "الشهر"],
  [/\bMAD\b/g, "درهم"],
  [/\bTotal\b/gi, "المجموع"],
  // "N vehicules disponibles" handled above; generic places
  [/\bplaces\b/gi, "مقاعد"],
  [/\bjours\b/gi, "أيام"],
  [/\bjour\b/gi, "يوم"],
  // ---- Mois français (formats date) ----
  [/\bjanvier\b/gi, "يناير"],
  [/\bfévrier\b/gi, "فبراير"],
  [/\bfevrier\b/gi, "فبراير"],
  [/\bmars\b/gi, "مارس"],
  [/\bavril\b/gi, "أبريل"],
  [/\bjuin\b/gi, "يونيو"],
  [/\bjuillet\b/gi, "يوليوز"],
  [/\baoût\b/gi, "غشت"],
  [/\baout\b/gi, "غشت"],
  [/\bseptembre\b/gi, "شتنبر"],
  [/\boctobre\b/gi, "أكتوبر"],
  [/\bnovembre\b/gi, "نونبر"],
  [/\bdécembre\b/gi, "دجنبر"],
  [/\bdecembre\b/gi, "دجنبر"],
  // mois abrégés (avec point)
  [/\bjanv\.?/gi, "ينا."],
  [/\bfévr\.?/gi, "فبر."],
  [/\bfevr\.?/gi, "فبر."],
  [/\bavr\.?/gi, "أبر."],
  [/\bjuil\.?/gi, "يول."],
  [/\bsept\.?/gi, "شت."],
  [/\boct\.?/gi, "أكت."],
  [/\bnov\.?/gi, "نون."],
  [/\bdéc\.?/gi, "دجن."],
  [/\bdec\.?/gi, "دجن."],
  // jours de la semaine
  [/\blundi\b/gi, "الإثنين"],
  [/\bmardi\b/gi, "الثلاثاء"],
  [/\bmercredi\b/gi, "الأربعاء"],
  [/\bjeudi\b/gi, "الخميس"],
  [/\bvendredi\b/gi, "الجمعة"],
  [/\bsamedi\b/gi, "السبت"],
  [/\bdimanche\b/gi, "الأحد"],

  [/\bAjouter un vehicule\b/g, "إضافة مركبة"],
  [/\bAjouter maintenance\b/g, "إضافة صيانة"],
  [/\bA jour\b/g, "محدّث"],
  [/\bActif\b/g, "نشط"],
  [/\bActive\b/g, "نشط"],
  [/\bAccident\b/g, "حادث"],
  [/\bAnnuler\b/g, "إلغاء"],
  [/\bAssurance\b/g, "التأمين"],
  [/\bBientot\b/g, "قريباً"],
  [/\bCategorie\b/g, "الفئة"],
  [/\bClients\b/g, "العملاء"],
  [/\bClient\b/g, "العميل"],
  [/\bConfirmer\b/g, "تأكيد"],
  [/\bDate\b/g, "التاريخ"],
  [/\bDocuments\b/g, "الوثائق"],
  [/\bEn cours\b/g, "قيد التنفيذ"],
  [/\bEn attente\b/g, "في الانتظار"],
  [/\bEn retard\b/g, "متأخر"],
  [/\bEnregistrer\b/g, "حفظ"],
  [/\bDisponible\b/g, "متاح"],
  [/\bGestion\b/g, "إدارة"],
  [/\bHistorique\b/g, "السجل"],
  [/\bKilometrage\b/g, "الكيلومترات"],
  [/\bMaintenance\b/g, "الصيانة"],
  [/\bMontant\b/g, "المبلغ"],
  [/\bPaiements\b/g, "المدفوعات"],
  [/\bPaiement\b/g, "الدفع"],
  [/\bParametres\b/g, "الإعدادات"],
  [/\bPeriode\b/g, "الفترة"],
  [/\bReservations\b/g, "الحجوزات"],
  [/\bReservation\b/g, "الحجز"],
  [/\bStatut\b/g, "الحالة"],
  [/\bSupprimer\b/g, "حذف"],
  [/\bModifier\b/g, "تعديل"],
  [/\bVehicules\b/g, "المركبات"],
  [/\bVehicule\b/g, "المركبة"],
  [/\bVidange\b/g, "تغيير الزيت"],
  [/\bVisite\b/g, "الفحص"],
  [/\bVignette\b/g, "الضريبة"],
  [/\bMarques\b/g, "العلامات"],
  [/\bMarque\b/g, "العلامة"],
  [/\bUtilisateurs\b/g, "المستخدمون"],
  [/\bUtilisateur\b/g, "المستخدم"],
  [/\bRoles\b/g, "الأدوار"],
]

function keepSpacing(original: string, translated: string) {
  const start = original.match(/^\s*/)?.[0] ?? ""
  const end = original.match(/\s*$/)?.[0] ?? ""
  return `${start}${translated}${end}`
}

function translateText(value: string) {
  const trimmed = value.trim()
  if (!trimmed) return value

  const exact = EXACT[trimmed]
  if (exact) return keepSpacing(value, exact)

  let next = trimmed
  for (const [pattern, replacement] of REPLACEMENTS) {
    next = next.replace(pattern, replacement)
  }

  return next === trimmed ? value : keepSpacing(value, next)
}

function translateElementAttributes(element: Element) {
  for (const attr of ["placeholder", "title", "aria-label"]) {
    const value = element.getAttribute(attr)
    if (!value) continue
    const translated = translateText(value)
    if (translated !== value) element.setAttribute(attr, translated)
  }
}

function translateNode(node: Node) {
  if (node.nodeType === Node.TEXT_NODE && node.textContent) {
    const translated = translateText(node.textContent)
    if (translated !== node.textContent) node.textContent = translated
    return
  }

  if (node.nodeType !== Node.ELEMENT_NODE) return

  const element = node as Element
  if (["SCRIPT", "STYLE", "TEXTAREA"].includes(element.tagName)) return

  translateElementAttributes(element)
  element.childNodes.forEach(translateNode)
}

export function ArabicRuntimeTranslator() {
  const locale = useLocale()

  useEffect(() => {
    if (locale !== "ar") return

    const run = () => translateNode(document.body)
    run()

    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        mutation.addedNodes.forEach(translateNode)
        if (mutation.type === "characterData") translateNode(mutation.target)
        if (mutation.type === "attributes" && mutation.target instanceof Element) {
          translateElementAttributes(mutation.target)
        }
      }
    })

    observer.observe(document.body, {
      childList: true,
      characterData: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["placeholder", "title", "aria-label"],
    })

    return () => observer.disconnect()
  }, [locale])

  return null
}
